// <auto-generated />
namespace LibraryWebSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mudando_nome_tabelas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mudando_nome_tabelas));
        
        string IMigrationMetadata.Id
        {
            get { return "201606131800357_mudando_nome_tabelas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
