//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_DropDownList_Multiplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGMENTO
    {
        public int SEG_ID { get; set; }
        public string DESCRICAO { get; set; }
        public string APAGADO { get; set; }
        public Nullable<System.DateTime> DTALTERACAO { get; set; }
        public string OPERADOR { get; set; }
        public Nullable<System.DateTime> DTAPAGADO { get; set; }
        public string OPERCADASTRO { get; set; }
        public Nullable<System.DateTime> DTCADASTRO { get; set; }
    }
}
