//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class postagem
    {
        public int id_postagem { get; set; }
        public int id_topico_forum { get; set; }
        public int id_usuario { get; set; }
        public string mensagem { get; set; }
        public Nullable<System.DateTime> data_publicacao { get; set; }
    
        public virtual topico_forum topico_forum { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
